[package]
name = "tui_confirm_dialog"
version = "0.1.6"
edition = "2021"
authors = ["Alessandro Crugnola <alessandro.crugnola@swisscom.com>"]
repository = "https://github.com/sephiroth74/tui-confirm-dialog"
description = "Ratatui dialogs"
license = "MIT"
readme = "./README.md"

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm"]

[dependencies]
ratatui = { version = "0.25.0", features = ["all-widgets"] }
rand = "0.8.5"
crossterm = { version = "0.27.0", optional = true}
regex = "1.10.2"
lazy_static = "1.4.0"
once_cell = "1.19.0"

[[example]]
name = "confirm"
required-features = ["crossterm"]

[[example]]
name = "popup"
required-features = ["crossterm"]