[package]
name = "tui_input_dialog"
version = "0.1.0"
edition = "2021"
authors = ["Alessandro Crugnola <alessandro.crugnola@swisscom.com>"]
repository = "https://github.com/sephiroth74/tui-confirm-dialog"
description = "Ratatui confirm dialog"
readme = "./README.md"

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm"]

[dependencies]
ratatui = { version = "0.24.0", features = ["all-widgets"] }
rand = "0.8.5"
crossterm = { version = "0.27.0", optional = true}

[[example]]
name = "confirm"
required-features = ["crossterm"]